// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Todo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type TodoList struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoList) Reset()         { *m = TodoList{} }
func (m *TodoList) String() string { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()    {}
func (*TodoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoList.Unmarshal(m, b)
}
func (m *TodoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoList.Marshal(b, m, deterministic)
}
func (m *TodoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoList.Merge(m, src)
}
func (m *TodoList) XXX_Size() int {
	return xxx_messageInfo_TodoList.Size(m)
}
func (m *TodoList) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoList.DiscardUnknown(m)
}

var xxx_messageInfo_TodoList proto.InternalMessageInfo

func (m *TodoList) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Integer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integer) Reset()         { *m = Integer{} }
func (m *Integer) String() string { return proto.CompactTextString(m) }
func (*Integer) ProtoMessage()    {}
func (*Integer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *Integer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integer.Unmarshal(m, b)
}
func (m *Integer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integer.Marshal(b, m, deterministic)
}
func (m *Integer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integer.Merge(m, src)
}
func (m *Integer) XXX_Size() int {
	return xxx_messageInfo_Integer.Size(m)
}
func (m *Integer) XXX_DiscardUnknown() {
	xxx_messageInfo_Integer.DiscardUnknown(m)
}

var xxx_messageInfo_Integer proto.InternalMessageInfo

func (m *Integer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "pb.Todo")
	proto.RegisterType((*TodoList)(nil), "pb.TodoList")
	proto.RegisterType((*Void)(nil), "pb.Void")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Integer)(nil), "pb.Integer")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x49, 0xda, 0x26, 0x53, 0xf1, 0x30, 0xa7, 0x98, 0x83, 0x86, 0x45, 0x21, 0x78,
	0xc8, 0xa1, 0xde, 0x05, 0xd1, 0x8b, 0xe0, 0x29, 0x14, 0x1f, 0x20, 0xce, 0xa0, 0x8b, 0xd2, 0x09,
	0xcd, 0x1c, 0xfa, 0x30, 0x3e, 0xac, 0xcc, 0xa6, 0x2a, 0xf4, 0xd0, 0xdb, 0x30, 0xff, 0xec, 0xf7,
	0xfd, 0x2c, 0x80, 0x0a, 0x49, 0x3b, 0xec, 0x44, 0x05, 0x93, 0xa1, 0xf7, 0xf7, 0x90, 0x6d, 0x84,
	0x04, 0xcf, 0x21, 0x09, 0x54, 0xba, 0xda, 0x35, 0x69, 0x97, 0x04, 0x42, 0x84, 0x4c, 0x79, 0xaf,
	0x65, 0x52, 0xbb, 0xa6, 0xe8, 0xe2, 0x6c, 0x3b, 0x92, 0x2d, 0x97, 0x69, 0xed, 0x9a, 0xbc, 0x8b,
	0xb3, 0xbf, 0x85, 0xdc, 0xde, 0xbf, 0x84, 0x51, 0xf1, 0x12, 0xe6, 0x46, 0x1f, 0x4b, 0x57, 0xa7,
	0xcd, 0x6a, 0x9d, 0xb7, 0x43, 0xdf, 0x5a, 0xd8, 0x4d, 0x6b, 0xbf, 0x80, 0xec, 0x55, 0x02, 0xf9,
	0x0a, 0xb2, 0xcd, 0x81, 0x17, 0x1d, 0xee, 0xdf, 0xe1, 0x2f, 0x60, 0xf9, 0xbc, 0x55, 0x7e, 0xe7,
	0xdd, 0x71, 0xa5, 0xf5, 0xb7, 0x83, 0xb9, 0xe1, 0x46, 0xbc, 0x82, 0xe5, 0x03, 0x51, 0xec, 0x3d,
	0x49, 0x78, 0xaf, 0xd5, 0x9f, 0xce, 0xcf, 0xf0, 0x06, 0x0a, 0x6b, 0x34, 0x5d, 0xc7, 0xc0, 0xc4,
	0xd5, 0xd9, 0xef, 0x89, 0x85, 0x7e, 0x86, 0xd7, 0x50, 0x3c, 0x7e, 0xf0, 0xdb, 0x67, 0x24, 0xad,
	0x2c, 0x3c, 0xb8, 0x8f, 0x60, 0xf0, 0xc4, 0x5f, 0xac, 0x7c, 0xf2, 0xac, 0x5f, 0xc4, 0x4f, 0xbd,
	0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x2c, 0x36, 0x2d, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodosClient is the client API for Todos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodosClient interface {
	AddTodo(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Todo, error)
	ListTodos(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TodoList, error)
	CheckTodo(ctx context.Context, in *Integer, opts ...grpc.CallOption) (*Todo, error)
	DeleteTodo(ctx context.Context, in *Integer, opts ...grpc.CallOption) (*Todo, error)
}

type todosClient struct {
	cc *grpc.ClientConn
}

func NewTodosClient(cc *grpc.ClientConn) TodosClient {
	return &todosClient{cc}
}

func (c *todosClient) AddTodo(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/pb.Todos/AddTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todosClient) ListTodos(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TodoList, error) {
	out := new(TodoList)
	err := c.cc.Invoke(ctx, "/pb.Todos/ListTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todosClient) CheckTodo(ctx context.Context, in *Integer, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/pb.Todos/CheckTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todosClient) DeleteTodo(ctx context.Context, in *Integer, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/pb.Todos/DeleteTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodosServer is the server API for Todos service.
type TodosServer interface {
	AddTodo(context.Context, *Text) (*Todo, error)
	ListTodos(context.Context, *Void) (*TodoList, error)
	CheckTodo(context.Context, *Integer) (*Todo, error)
	DeleteTodo(context.Context, *Integer) (*Todo, error)
}

func RegisterTodosServer(s *grpc.Server, srv TodosServer) {
	s.RegisterService(&_Todos_serviceDesc, srv)
}

func _Todos_AddTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).AddTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todos/AddTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).AddTodo(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todos_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todos/ListTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).ListTodos(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todos_CheckTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).CheckTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todos/CheckTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).CheckTodo(ctx, req.(*Integer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todos_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todos/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).DeleteTodo(ctx, req.(*Integer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Todos",
	HandlerType: (*TodosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTodo",
			Handler:    _Todos_AddTodo_Handler,
		},
		{
			MethodName: "ListTodos",
			Handler:    _Todos_ListTodos_Handler,
		},
		{
			MethodName: "CheckTodo",
			Handler:    _Todos_CheckTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _Todos_DeleteTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
